name: Release
on:
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Package Charts
        run: |
          helm package ./charts/app
          helm package ./charts/helm-chart-sources

      - name: Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            app-${{ env.RELEASE_VERSION }}.tgz
            helm-chart-sources-${{ env.RELEASE_VERSION }}.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
